sudo: false
language: c
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- echo $HOME
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
script:
- stack --no-terminal --install-ghc build --fast --only-dependencies
- stack exec milkshake -- sitemap.yaml -c
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - ./.stack-work
deploy:
  provider: s3
  access_key_id: AKIAIU3QHNFTGN4TN5GA
  secret_access_key:
    secure: J9tMGR0moNo3vxaMqDRoDRK1x5yj9n/Bv3gfJnkJxzpyA58f0nGVPc8vppu0NgXzAqt7po0jW+ahh92EGueVIdmpn7FbaG1xrxxWZ4zl6mnrO3fOmU247iH3BGTXj0i+qRhk2BMSmyIDbygAqXB9CvspQiWkyArJ1xJ/+JlxbTxfFJ4cBzx1gbv9TKiQWPklFYqYTpMdLa1VinLIyWKT11z/RrTamKr3OPsj27o+vwYwUqonOLDzcfN2EdOOqyGsK0oTZuZJbMERYLWWVTioY44bSh/4+t1APrK8nhbI1IonvU7rYBudJNXehJ2IT5zPu4BgAtPpadmgrhHlUHogGTCRetG/bbYtK0+D6aWLzJgW8dz9CYgbsSW+NmocIsX9mlk+T0NjOXFAsNBHchBNv8a40e+BtRI5Nd8X45wcypHFtJK+x+FEKZIKBgk6oMXrmdHut8MJ0HrcGHijlnPOQ0FRwJvH7fPsRXuDrLkF2W90AmwyvjS/vNb6lZWLPSkQnLn92zCDmMZaP1YT5BUNwjj/zfDpafTppBoT7oUSFgzJfTojZHOjQFefh6b739y/91szVHg6iNpxaoaqsJPpxHqavZR7w4Hue3Wx+LgXFEa/5ojQkjvJHH+8sFfusrLHOdb7czOa4aoS/Y5HfzdP90I6p+LOyx0dv75CGEM8TV8=
  bucket: rinerscivally.com
  local-dir: build/site
  acl: public_read
  region: us-west-1
  skip_cleanup: true
  on:
    repo: schell/rinerscivally.com
